---
- name: Create file on Linux
  hosts: rhel9:rhel8:linux
  gather_facts: false
  tasks:
    - name: Create test.txt on Linux
      ansible.builtin.file:
        path: /home/lcl_admin/test.txt
        state: touch

- name: Create file on Windows
  hosts: windows
  gather_facts: false
  tasks:
    - name: Create test.txt on Windows
      ansible.windows.win_file:
        path: C:\Users\Public\test.txt
        state: touch